# Generated by Django 3.2.5 on 2021-08-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csvfiles')),
                ('symbole', models.CharField(max_length=255, null=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('open', models.CharField(max_length=255, null=True)),
                ('high', models.CharField(max_length=255, null=True)),
                ('low', models.CharField(max_length=255, null=True)),
                ('close', models.CharField(max_length=255, null=True)),
                ('volume', models.CharField(max_length=255, null=True)),
                ('adjclose', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
